# Generated by Django 5.1.6 on 2025-02-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventmembers_delete_eventitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user_profile',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='eventmembers',
            old_name='user_profile',
            new_name='member',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='eventmembers',
            name='date_time',
        ),
        migrations.AddField(
            model_name='event',
            name='date_created',
            field=models.DateField(default='2025-02-19'),
        ),
        migrations.AddField(
            model_name='event',
            name='date_event',
            field=models.DateField(default='2025-02-19'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Test', max_length=100),
        ),
        migrations.AddField(
            model_name='eventmembers',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventmembers',
            name='date_invited',
            field=models.DateField(default='2025-02-19'),
        ),
    ]
