# Generated by Django 5.1.6 on 2025-02-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_user_profile_event_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_event',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventmembers',
            name='date_invited',
            field=models.DateField(auto_now_add=True),
        ),
    ]
